### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by VirdanTheBurden**
Hey boss, got this new readme done. What do you think?

### CODE REVIEW

**Comment by Kronifer** [comment]
Maybe a little less cat spam we dont wanna scare people ya know

**Comment by VirdanTheBurden** [comment]
alright, dropping catspam a bit

**Comment by Kronifer** [comment]
Like maybe half the cat spam, yeah

**Comment by VirdanTheBurden** [comment]
updated again, reduced the catspam by a good amount

**Comment by Kronifer** [comment]
Approved this is beautiful

**Pull request merged**
